### ISSUE TITLE
Error loading shared library libsqlite3.so.0

### ISSUE THREAD

**Issue by webalexeu** [nakla/sbfspot#1]
Hello,

I've started a fresh new container and I got this:
`
Error loading shared library libsqlite3.so.0: No such file or directory (needed by /usr/local/bin/sbfspot.3/SBFspot_sqlite)
Error loading shared library libsqlite3.so.0: No such file or directory (needed by /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite)
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_bind_int64: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_busy_timeout: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_libversion: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_reset: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_exec: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_bind_int: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_column_double: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_errmsg: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_column_type: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_step: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_column_int64: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_close: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_column_text: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_bind_null: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_bind_text: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_clear_bindings: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_threadsafe: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_finalize: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_prepare_v2: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspot_sqlite: sqlite3_open_v2: symbol not found
Sleeping 300 seconds.
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_column_text: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_close: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_open_v2: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_exec: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_column_int64: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_finalize: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_column_type: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_step: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_errmsg: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_prepare_v2: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_threadsafe: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_busy_timeout: symbol not found
Error relocating /usr/local/bin/sbfspot.3/SBFspotUploadDaemon_sqlite: sqlite3_column_double: symbol not found
`

Thank you for your support,
Alex

**Comment by nakla** [comment]
Hi, thanks for your report. SQLite usage should now work. I forgot to include the sqlite-libs package. Best regards

**Comment by webalexeu** [comment]
Thank you for the quick fix
