### ISSUE TITLE
standard_init_linux.go:228 exec user process caused: exec format error on latest image

### ISSUE THREAD

**Issue by m11tch** [nakla/sbfspot#10]
I'm not sure what has changed in the latest image, but upgrading my existing container to this image caused the container to exit with the following error: 

`standard_init_linux.go:228 exec user process caused: exec format error`

For now I reverted to :v1.0, because I don't have time for further troubleshooting at this moment.

**Comment by nakla** [comment]
Possibly due to a docker bug, your system pulled an image for the wrong architecture? Are you using an rpi 1 or rpi zero?
On AMD64 arch image works without problem.

**Comment by m11tch** [comment]
It seems you're right, it pulled the ARM image instead of AMD64.
