### ISSUE TITLE
userid 5000

### ISSUE THREAD

**Issue by TerrorSource** [nakla/sbfspot#11]
I used to run the sbfspot on my Synology, tried to update to the latest version and i have issues running it.

When i login via SSH and run " awk -F: '{ print $1}' /etc/passwd " and check all users for their ID i cannot find UserID 5000 or GroupID 5000

Do i need to created it manually?

Log from the container:
```
Please change file permissions of SBFspot.cfg or ensure, that the "OutputPath" and "OutputPathEvents" Options
point to the Directory /var/sbfspot/...
Mapped Data directory is not writeable for user with ID 5000.
Please change file permissions accordingly and restart the container.
```

**Comment by nakla** [comment]
No just change the ownership of the files directories. E.g. `chown -R 5000:5000 /var/sbfspot`
You don'T need the user created on the nas. Hope this works too on the synology.

**Comment by TerrorSource** [comment]
I did the following to fix this

1. SSH into synology
2. sudo su (so you are root)
3. chown -R 5000:5000 /volume1/docker/sbfspot/
4. start container

/var/sbfspot is the location within the docker but is redirected to /volume/docker/sbfspot on my synology.

**Comment by nakla** [comment]
great
