### ISSUE TITLE
UID and PGID

### ISSUE THREAD

**Issue by Robindeko** [nakla/sbfspot#16]
I would like to run this container on my Synology NAS.
Unfortunately, it is not possible to change the UID and PGID's for users on a Synology.
Would it be possible to set a correct UID and PGID using environment variables?

Thanks in advance!

**Comment by nakla** [comment]
Hi, sure that can be implemented. But it should also be possible to change the IDs on a Synology, as you can open a ssh shell on those NAS Systems.

**Comment by Robindeko** [comment]
Thanks for your response.
Yes you can open an SSH session on the NAS, but there is no usermod command.
Furthermore, you can change the passwd file manually, but this gives issues in the GUI of the NAS.
The concencus on the internet seems to be, that you need to set the correct UIDs and PGIDs using ENV settings.

**Comment by nakla** [comment]
chown 5000:5000 /your/sbfspot/dir doesn't work?

**Comment by Robindeko** [comment]
Wow, guess I learned something new today.
I assumed a user would need to exist with UID 5000, but the command works :)
(I had to add a -R to make it recursive)

Seems to be working now (will need to check once it's not dark here)
Thanks a lot!

**Comment by nakla** [comment]
No problem, I wanted the container user not to be present in the host system so he has minimum file permissions.
