### ISSUE TITLE
Update to latest SBFspot version?

### ISSUE THREAD

**Issue by bodomenke** [nakla/sbfspot#18]
I just installed a new SMA hybrid inverter (SUNNY TRIPOWER 6.0 SE). 
nakla/sbfspot responded to me with:

> Unknown Device Class. Report this issue at https://github.com/SBFspot/SBFspot/issues with following info: 0x00001F49 and Device Class=...

So, I opened an issue at SBFspot and got the immediate answer, that SBFspot supports hybrid inverters since version 3.9.7. I checked version of nakla/sbfspot and realized it is on 3.8.4.

Do you mind to refresh to the latest SBFspot version?

Many thanks
Bodo

**Comment by nakla** [comment]
Hi, sorry for the delay -  I am going to update the container, I hope in the next days...

**Comment by nakla** [comment]
Container was updated on friday
