### ISSUE TITLE
dual inverter

### ISSUE THREAD

**Issue by arno58** [nakla/sbfspot#20]
I would like to use your docker image but i have two inverters.
I could create two docker two docker images but they would run in to sharing conflicts.

ps
I found a dock image (bigrob8181/monitor) who uses 
   
    network_mode: host
    cap_add:
      - NET_ADMIN
  
to create a secure docker image with access to bluetooth device

**Comment by nakla** [comment]
Hi, you only need `network_mode: host` - `NET_ADMIN` is not necessary (you can see that in my docker-compose.yaml example at the end of the readme).
You can configure 2 inverters simply in the configfile. 
I believe you just have to set BTAddress to one of your inverters, and set the MTS_Enabled variable to 1.
In both inverters, you have to set the same ID - mine have a rotary switch, but they were set to the same id already in factory, just in case the is different in your ones.

**Comment by arno58** [comment]
Thank you for your quick response.
A) i thought that extra parameter was meant to limit root access to only
network devices, i will check the running processes.
B) all the solar panels are on my roof, one inverter is owned by my
neighbour and stored in different pvoutput accounts; if there is a
difference between them i get an Allert.

Op za 18 nov. 2023 01:03 schreef nakla ***@***.***>:

**Comment by nakla** [comment]
Ok, I don't use pvoutput, I don't know if the upload can handle two accounts in one instance. I believe you find informations about it in the docu. If that is not possible, you can simply run two instances of the sbfspot container with two separate uploads.
