### ISSUE TITLE
[question] From regular install to docker install

### ISSUE THREAD

**Issue by Depechie** [nakla/sbfspot#5]
I would love to try this docker container version of sbfspot, but was wondering if I could just drop my regular install configs?
The thing I mostly wondering about are the paths that are already in the configs.

```
OutputPath=/home/pi/smadata/%Y
OutputPathEvents=/home/pi/smadata/%Y/Events
SQL_Database=/home/pi/smadata/SBFspot.db
```

With the docker container we map 2 volumes, so the paths will be new, but what do I put in the cfg's?
Would this be correct?

```
OutputPath=/etc/sbfspot/%Y
OutputPathEvents=/etc/sbfspot/%Y/Events
SQL_Database=/var/sbfspot/SBFspot.db
```

**Comment by nakla** [comment]
No, 
```
OutputPath=/var/sbfspot/%Y
OutputPathEvents=/var/sbfspot/%Y/Events
```

OutputPath and OutputPathEvents are used to store csv files (should be explained in your SBFspot.cfg). 


...taken from the readme
Volumes

    /etc/sbfspot => directory for your configuration files
    /var/sbfspot => data directory (for storing csv files or sqlite database file)

The mapped host volumes should be read- and writeable for user with ID 5000 or group with ID 5000.

Feel free to make your own subdirs e.g.
```
OutputPath=/var/sbfspot/productionData
OutputPathEvents=/var/sbfspot/Events
SQL_Database=/var/sbfspot/database/SBFspot.db
```
You can also just start the container and should get error messages, if there are issues in your path configurations.

**Comment by Depechie** [comment]
hey @nakla the container is running great! My data is being read from the inverter.
But when I enable the upload deamon through the ENABLE_SBFSPOT_UPLOAD variable setting it to 1, I still don't see the values being pushed to PVOutput.
I added my inverter SN to plant ID mapping and API key in the config.
The logs mention the readouts each 600 seconds, but nothing about the upload.

Not setting the 2 pvoutput params in the upload config does give log warnings... but adding them does not seem to fix it?
Any tips on how to check this. Getting into the container is also failing for bash?

**Comment by Depechie** [comment]
Nevermind! Needed to add the correct log folder in the config!
