### ISSUE TITLE
Upgrade docker to latest and have segmentation error now

### ISSUE THREAD

**Issue by GRiDlockUK** [nakla/sbfspot#7]
SBFspot V3.8.2
Yet another tool to read power production of SMA solar inverters
(c) 2012-2021, SBF (https://github.com/SBFspot/SBFspot)
Compiled for Linux (LE) 32 bit with SQLite support
SBFspotUploadDaemon Version 3.0.1
Loglevel=1
LogDir=/var/sbfspot/log/
Segmentation fault
Sun Jan  0 00:100:4174038  1900
Sleeping 600 seconds.

**Comment by nakla** [comment]
Hi, the image worked in earlier versions? 
Do you use the arm v6 or arm v7 version?
Do you run the image on a rpi? Which one?

**Comment by GRiDlockUK** [comment]
Sorted -- issue appears to be that the date was not set. Found article about the issue and gave the container "priv" access.  Date now fine the shell and uploading data again..

https://pvoutput.org/list.jsp?userid=2182

Thanks
