### ISSUE TITLE
sqlite errors

### ISSUE THREAD

**Issue by aidbish** [nakla/sbfspot#8]
Hi
When i bring up the container i get the following errors in the log

any ideas?

Error: near line 3: table Config already exists
Error: near line 9: UNIQUE constraint failed: Config.Key
Error: near line 11: table Inverters already exists
Error: near line 28: table vwInverters already exists
Error: near line 39: table SpotData already exists
Error: near line 59: table vwSpotData already exists
Error: near line 99: table DayData already exists
Error: near line 108: table vwDayData already exists
Error: near line 117: table MonthData already exists
Error: near line 125: table vwMonthData already exists
Error: near line 132: table EventData already exists
Error: near line 148: table vwEventData already exists
Error: near line 159: table Consumption already exists
Error: near line 166: table vwConsumption already exists
Error: near line 176: table vwAvgConsumption already exists
Error: near line 184: table vwAvgSpotData already exists
Error: near line 206: table vwPvoData already exists
Error: near line 232: table SpotDataX already exists
Error: near line 3: table Config already exists
Error: near line 9: UNIQUE constraint failed: Config.Key
Error: near line 11: table Inverters already exists
Error: near line 28: table vwInverters already exists
Error: near line 39: table SpotData already exists
wal
Error: near line 59: table vwSpotData already exists
Error: near line 99: table DayData already exists
Error: near line 108: table vwDayData already exists
Error: near line 117: table MonthData already exists
Error: near line 125: table vwMonthData already exists
Error: near line 132: table EventData already exists
Error: near line 148: table vwEventData already exists
Error: near line 159: table Consumption already exist
Error: near line 166: table vwConsumption already exists
Error: near line 176: table vwAvgConsumption already exists
Error: near line 184: table vwAvgSpotData already exists
Error: near line 206: table vwPvoData already exists
Error: near line 232: table SpotDataX already exists

**Comment by nakla** [comment]
You read the Readme about the Database initialization?
The last two sentences are:
After the Database is set up, please delete the three database initialization variables. For security reasons, normal operation is prohibited, if administrative accounts are provided. 

If you did that, please post the your startup command.
